import type { Metadata } from "next";
import { Underdog } from "next/font/google";
import "./globals.css";

const underDog = Underdog({
  variable: "--font-underdog",
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${underDog.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
